### ISSUE TITLE
Link redirects to 404

### ISSUE THREAD

**Issue by Utkarsh299-tech** [Michael0x2a/curated-programming-resources#35]
Hi!
The following link of the **list of free programming books and resources on GitHub** is not working.
I have attached the screenshot of the link for your reference.

![Screenshot (362)](https://user-images.githubusercontent.com/60184229/126063153-562bdbe3-a82f-41d2-a906-86b758834f1a.png)

**Comment by desrtfx** [comment]
Thanks for bringing this to our attention. Sorry for the late reply.

The original link the free books were posted under has changed (again). I have rectified the issue.

FYI: new link  https://github.com/EbookFoundation/free-programming-books
